-- db/migrations/create_market_digests.sql
-- P6-C: Daily Morning Brief + Closing Digest for Indian equity market
-- Run once in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS market_digests (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  digest_type      TEXT        NOT NULL CHECK (digest_type IN ('MORNING', 'CLOSING')),
  digest_date      DATE        NOT NULL,
  headline_count   INTEGER     DEFAULT 0,
  top_themes       JSONB       DEFAULT '[]',
  summary          TEXT,
  key_events       JSONB       DEFAULT '[]',
  market_mood      TEXT        CHECK (market_mood IN ('BULLISH','BEARISH','NEUTRAL','VOLATILE','MIXED')),
  nifty_signal     TEXT,
  sectors_in_focus JSONB       DEFAULT '[]',
  raw_headlines    JSONB       DEFAULT '[]',
  created_at       TIMESTAMPTZ DEFAULT now()
);

-- One row per type per day; upsert is idempotent
CREATE UNIQUE INDEX IF NOT EXISTS market_digests_type_date_idx
  ON market_digests (digest_type, digest_date);

-- Row-level security (service_role bypasses by default)
ALTER TABLE market_digests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all" ON market_digests
  FOR ALL USING (true) WITH CHECK (true);

COMMENT ON TABLE market_digests IS
  'P6-C: Daily Morning Brief (08:45 IST) and Closing Digest (16:20 IST) for the Indian equity market. Generated by agents/market_digest.py via Claude Haiku.';
